// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJ89hU2oBIQhS4zgwsqWYgoG27Nzu6zy8',
    appId: '1:182609954574:web:2a0e47170565774f5c795f',
    messagingSenderId: '182609954574',
    projectId: 'webdashboard-c6d24',
    authDomain: 'webdashboard-c6d24.firebaseapp.com',
    storageBucket: 'webdashboard-c6d24.appspot.com',
    measurementId: 'G-EKY321XQ1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi-75j1tw2cTmJAN6gSmIhY3EnhiFie24',
    appId: '1:182609954574:android:d968d233ded7317d5c795f',
    messagingSenderId: '182609954574',
    projectId: 'webdashboard-c6d24',
    storageBucket: 'webdashboard-c6d24.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIYdl06qb-5I-UjuKlEu2lbLKl9H9j1q4',
    appId: '1:182609954574:ios:80d88eea90d6410f5c795f',
    messagingSenderId: '182609954574',
    projectId: 'webdashboard-c6d24',
    storageBucket: 'webdashboard-c6d24.appspot.com',
    iosClientId: '182609954574-ossqjo3grau108lknc5kpap0pbn52vvr.apps.googleusercontent.com',
    iosBundleId: 'com.example.webdashboard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIYdl06qb-5I-UjuKlEu2lbLKl9H9j1q4',
    appId: '1:182609954574:ios:80d88eea90d6410f5c795f',
    messagingSenderId: '182609954574',
    projectId: 'webdashboard-c6d24',
    storageBucket: 'webdashboard-c6d24.appspot.com',
    iosClientId: '182609954574-ossqjo3grau108lknc5kpap0pbn52vvr.apps.googleusercontent.com',
    iosBundleId: 'com.example.webdashboard',
  );
}
